### PR TITLE
cli: Allow client libraries to use `IO` to create `ExtensionImpl`

### PR DESCRIPTION
**Pull request by langston-barrett**
This is needed in Macaw.

### CODE REVIEW

**Review by RyanGlScott — COMMENTED** [review]
I am a bit surprised that you'd need `IO` just to create an `ExtensionImpl`. Can you say more about how it's used in Macaw? (I'm sure there is a good reason, but I'm having trouble seeing it without further context.)

**Comment by langston-barrett** [comment]
Yeah! The problem is that to create a `macawExtensions`, you need a `MacawArchEvalFn`, which, at least for x86_64, requires something called `SymFns`, which you create with `newSymFns ::~ sym -> IO SymFns`.

**Comment by langston-barrett** [comment]
Also, to create a `MemModelConfig`, I'll need access to `bak`, not just `sym` (see most recent commit).

**Comment by langston-barrett** [comment]
... and in fact, [`newGlobalMemoryWith`](https://github.com/GaloisInc/macaw/blob/3dfc22bf4108db1ec1c9d5bb3a7b834e0eb8686d/symbolic/src/Data/Macaw/Symbolic/Memory.hs#L208) even needs to know `sym ~ WEB.ExprBuilder t st fs`...

**Comment by langston-barrett** [comment]
See https://github.com/GaloisInc/macaw/pull/423 for what I'm trying to do with this.

**Review by RyanGlScott — APPROVED** [review]
Ah, right.

**Pull request merged**
