### PR TITLE
Cfg syntax

### PR DESCRIPTION
**Pull request by robdockins**
Pull request to track David's work on a direct syntax for Crucible programs.

For now, this PR is for discussion and ease of viewing code changes only; not ready to merge.

### CODE REVIEW

**Comment by robdockins** [comment]
@david-christiansen, Where are we on this?

**Comment by david-christiansen** [comment]
Two things to do:

1. The error messages were bad enough to make it so that I had to consult the source when I had messages. I made a better parsing setup that generates good errors without a lot of manual work, and am porting the system to use it. Mostly done with that.

2. You mentioned that you had a branch that was set up to do more than just parse and SSA-convert them. I need to get that code cherry-picked in.

**Comment by robdockins** [comment]
OK, let's go ahead an look at merging this as soon as point 1) is done.  I was having trouble keeping that code up to date as this branch drifted from master, so doing a cherry-pick isn't really possible.  I'll put that together, or help you to do it, after we merge.

**Comment by david-christiansen** [comment]
I think it's ready for your initial experimentation.

**Comment by david-christiansen** [comment]
The Emacs mode for editing the syntax in question is here: https://github.com/GaloisInc/crucibler-mode

**Pull request merged**
