### PR TITLE
Implement byte-to-char casts for crucible-mir.

### PR DESCRIPTION
**Pull request by sauclovian-g**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks, @sauclovian-g! I can believe that this fixes the issue, but I would feel better if we added a regression test alongside it. Can you add [this test case](https://github.com/GaloisInc/crucible/issues/1190#issuecomment-2022567787) to `crux-mir`'s test suite? I'm not too bothered about the exact location where we put the test—somewhere in `test/conc_eval/num` would work, for instance.

**Comment by RyanGlScott** [comment]
@sauclovian-g, do you plan on finishing this?

**Comment by sauclovian-g** [comment]
Yes, we need it for FV, just disorganized/behind on everything :-|

**Comment by sauclovian-g** [comment]
This should be ready to go now.

(I think I should rebase it on master before merging, and probably squash the two commits together too, but probably you should look at it first)

**Review by RyanGlScott — APPROVED** [review]
Thanks for pushing this one over the finish line!

**Comment by sauclovian-g** [comment]
I rebased it on master and squashed the commits together. Since it's small and isolated this is pretty harmless, and it's been sitting around for a while.

**Pull request merged**
